### ISSUE TITLE
How does the bot database work? 

### ISSUE THREAD

**Issue by pedroricardo** [Repulser/Protector#7]
How does the bot database work? Do I need to create one?

**Comment by Repulser** [comment]
You need to run mongodb localhost on the default port.

**Comment by pedroricardo** [comment]
Yes, you can get vlw

**Comment by pedroricardo** [comment]
I did it, thank you

**Comment by pedroricardo** [comment]
@Repulser another doubt, is there a command that I can let a role specify use the administration commands?
